import sys
print("Vitej! Tohle je generator stupnu vitezu!")
prvni_misto = input("Zapis prvni misto ")
druhe_misto = input("Zapis druhe misto ")
treti_misto = input("Zapis treti misto ")
print("                " + prvni_misto)
print("⠀            ⢀⣀⣀⣀⣀⣀⣀⣀⣀⣀⡀⠀")
print("             ⢸⣿⣿⡿⠿⠿⢿⣿⣿⣿⡇")
print("             ⢸⣿⣿⣿⣶⠀⢸⣿⣿⣿⡇")
print("             ⢸⣿⣿⣿⠿⠀⠸⢿⣿⣿⡇")
print("             ⢸⣿⣿⣿⣶⣶⣶⣾⣿⣿⡇")
print("     " + druhe_misto)
print("    ⣤⣤⣤⣤⣤⣤⣤⣤⣤⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇")
print("    ⣿⣿⣟⢉⣉⠉⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇" + treti_misto)
print("⠀   ⣿⣿⣿⣿⠟⢀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⣶⣶⣶⣶⣶⣶⣶⠀")
print("⠀   ⣿⣿⣟⠁⠐⠛⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣉⣉⡉⢹⣿⣿ ")
print("    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣉⡀⢸⣿⣿")
print("    ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣉⣉⣁⣼⣿⣿")
print("    ⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛")
input("Stiskni Enter pro ukonceni programu")
sys.exit() 